apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: core-state
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisType
      value: node
    - name: redisDB
      value: 7
    - name: redisHost
      value: tkeel-middleware-redis-master:6379
    - name: redisPassword
      secretKeyRef:
        name: tkeel-middleware-redis
        key: redis-password
scopes:
  - core
