server:
  app_port: 6789
logger:
  dev: true
  level: DEBUG

tseries:
  name: influxdbx
  properties:
    - key: url
      value: http://localhost:8086/
    - key: token
      value: 
    - key: org
      value: 
    - key: bucket
      value: 

