apiVersion: v2
appVersion: 0.4.1
description: A Helm chart for Kubernetes
name: core
type: application
version: 0.4.1
dependencies:
  - name: clickhouse
    repository: https://charts.kubesphere.io/test
    version: 0.1.0
maintainers:
  - email: tkeel@yunify.com
    name: tkeel
