// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: v1/placement.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterStatemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterStatemReq) Reset() {
	*x = RegisterStatemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_placement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterStatemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStatemReq) ProtoMessage() {}

func (x *RegisterStatemReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_placement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStatemReq.ProtoReflect.Descriptor instead.
func (*RegisterStatemReq) Descriptor() ([]byte, []int) {
	return file_v1_placement_proto_rawDescGZIP(), []int{0}
}

type RegisterStatemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterStatemResp) Reset() {
	*x = RegisterStatemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_placement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterStatemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStatemResp) ProtoMessage() {}

func (x *RegisterStatemResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_placement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStatemResp.ProtoReflect.Descriptor instead.
func (*RegisterStatemResp) Descriptor() ([]byte, []int) {
	return file_v1_placement_proto_rawDescGZIP(), []int{1}
}

type ReportStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportStatusReq) Reset() {
	*x = ReportStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_placement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusReq) ProtoMessage() {}

func (x *ReportStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_placement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusReq.ProtoReflect.Descriptor instead.
func (*ReportStatusReq) Descriptor() ([]byte, []int) {
	return file_v1_placement_proto_rawDescGZIP(), []int{2}
}

type ReportStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportStatusResp) Reset() {
	*x = ReportStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_placement_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResp) ProtoMessage() {}

func (x *ReportStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_placement_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResp.ProtoReflect.Descriptor instead.
func (*ReportStatusResp) Descriptor() ([]byte, []int) {
	return file_v1_placement_proto_rawDescGZIP(), []int{3}
}

var File_v1_placement_proto protoreflect.FileDescriptor

var file_v1_placement_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x32, 0x90, 0x01,
	0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0b,
	0x52, 0x65, 0x70, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_placement_proto_rawDescOnce sync.Once
	file_v1_placement_proto_rawDescData = file_v1_placement_proto_rawDesc
)

func file_v1_placement_proto_rawDescGZIP() []byte {
	file_v1_placement_proto_rawDescOnce.Do(func() {
		file_v1_placement_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_placement_proto_rawDescData)
	})
	return file_v1_placement_proto_rawDescData
}

var file_v1_placement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_placement_proto_goTypes = []interface{}{
	(*RegisterStatemReq)(nil),  // 0: proto.RegisterStatemReq
	(*RegisterStatemResp)(nil), // 1: proto.RegisterStatemResp
	(*ReportStatusReq)(nil),    // 2: proto.ReportStatusReq
	(*ReportStatusResp)(nil),   // 3: proto.ReportStatusResp
}
var file_v1_placement_proto_depIdxs = []int32{
	0, // 0: proto.Placement.Register:input_type -> proto.RegisterStatemReq
	2, // 1: proto.Placement.RepotStatus:input_type -> proto.ReportStatusReq
	1, // 2: proto.Placement.Register:output_type -> proto.RegisterStatemResp
	3, // 3: proto.Placement.RepotStatus:output_type -> proto.ReportStatusResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_placement_proto_init() }
func file_v1_placement_proto_init() {
	if File_v1_placement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_placement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterStatemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_placement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterStatemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_placement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_placement_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_placement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_placement_proto_goTypes,
		DependencyIndexes: file_v1_placement_proto_depIdxs,
		MessageInfos:      file_v1_placement_proto_msgTypes,
	}.Build()
	File_v1_placement_proto = out.File
	file_v1_placement_proto_rawDesc = nil
	file_v1_placement_proto_goTypes = nil
	file_v1_placement_proto_depIdxs = nil
}
