server:
  name: core3
  http_port: 6787
  grpc_port: 31231
  tseries_servers:
    - name: time_series
      enabled: true
      sources:
        - name: source_time_series
          type: pubsub
          properties:
            pubsub: core-pubsub
            topics: ts
      batch_queue:
        name: queue_tseries
        max_batching: 1000
        max_pending_messages: 5
        batching_max_flush_delay: 10
logger:
  output_json: true
placement:
  port: 5002
  raft:
    servers:
      - id: core
        addr: 172.31.165.222:9112
      - id: core2
        addr: 172.31.165.222:9113
      - id: core3
        addr: 172.31.165.222:9114